[package]
name = "abbs"
version = "0.2.2"
edition = "2024"
license = "MIT"
authors = ["Thomas Habets <thomas@habets.se>"]
repository = "https://github.com/ThomasHabets/abbs"
description = "An amateur radio BBS"
keywords = ["amateur", "radio", "bbs", "ax25"]

[dependencies]
agw = "0.9.0"
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
env_logger = "0.11.8"
futures-util = "0.3.31"
log = "0.4.28"
rusqlite = "0.37.0"
zmodem2 = "0.7.2"
tokio = { version = "1.48.0", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }

[patch.crates-io]
agw = { path = "../agw" }
